name: "coverage"
on:
  pull_request:
    branches:
      - main
      - Jest
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter-code/server #this runs the test cases in server
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies for test
        run: |
          npm install cross-fetch
          npm install
      - name: Set up environment variables
        env:
          ENV_FILE_CONTENTS: ${{ secrets.ENV_FILE }}
        run: echo "${ENV_FILE_CONTENTS}" > .env
      - name: Test
        run: npm test -- --coverage


#going to comment out client test cases for now

#client-tests:
 # runs-on: ubuntu-latest
 # defaults:
  #  run:
    #   working-directory: ./starter-code/client
#   steps:
  #   - uses: actions/checkout@v3
   #  - name: Install dependencies for client tests
    #   run: npm install
    # - name: Run client tests
      # run: npm test -- --coverage