name: "coverage"
on:
  pull_request:
    branches:
      - main
      - Jest
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter-code/server
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies for test
        run: |
          npm install cross-fetch
          npm install
      - name: Set up environment variables
        env:
          ENV_FILE_CONTENTS: ${{ secrets.ENV_FILE }}
        run: echo "${ENV_FILE_CONTENTS}" > .env
      - name: Test
        run: npm test -- --coverage
