name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
jobs:
  Backend-Functions: 
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: /home/runner/work/RateMyPotty/RateMyPotty/server
    steps: 
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run Test
        run: npm test
