name: "coverage"
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies for test
        run: |
          npm install
      - name: Test
        run: npm test 
