name: 'coverage'
on:
  push:
    branches:
      - master
      - main
jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.7' 
      - run: npm install
      - run: npm run test -- --coverage
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          test_script: npm run test -- --coverage
          prnumber: ${{ steps.findPr.outputs.number }}
