name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        defaults: 
              run:
                working-directory: /starter-code/server
        steps:
              - uses: actions/checkout@v2
              - name: Install dependencies
                run: npm install
              - name: Run Test
                run: npm test
